name: PICK2024-T2 Workflow

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no Repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: 'main'
          set-safe-directory: '/home/runner/work/LINUXtips-Giropops-Senhas/LINUXtips-Giropops-Senhas'

  lint:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: versao-01/Dockerfile
          output-file: versao-01/Hadolint-Giropops-Output
  
  update-pr:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  